version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - my_network
    volumes:
      - mongodbdata:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    hostname: rabbitmq
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - my_network

  # ecomproductservice:
  #   image: ecomproductservice:latest
  #   build:
  #     context: ../Ecom.ProductService
  #     dockerfile: Dockerfile
  #   networks:
  #     - my_network
  #   depends_on:
  #     - rabbitmq
  #     - mongo
  #   ports:
  #     - 5000:80
  #     - 5001:443

volumes:
  mongodbdata:
  rabbitmqdata:

networks:
  my_network:
